server:
  port: 8761
eureka:
  client:
    eureka-connection-idle-timeout-seconds: 5
    fetch-registry: false
    register-with-eureka: false
  server:
    peer-node-read-timeout-ms: 10000
    renewal-percent-threshold: 0.85